[project]
name = "DESAFIO_R3"
version = "0.1.0"
description = "Recomendador de repostajes/carga con ahorro y sostenibilidad (FastAPI)."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "fastapi>=0.115.0",
  "pandas>=2.0",
  "numpy>=1.26",
  "scikit-learn>=1.3",
  "lightgbm>=4.0",
  "python-multipart>=0.0.9",
]

[project.optional-dependencies]
dev = [
  "httpx>=0.27",
  "ruff>=0.5",         # lint
  "black>=24.8.0",     # format
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
# uv gestionará el virtualenv automáticamente en .venv
managed = true

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
